name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BASEURL: ${{ vars.BASEURL }}
  USER: ${{ secrets.USER }}
  PASSWORD: ${{ secrets.PASSWORD }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Local

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Start API
        working-directory: ./CatCafeAPI
        run: |
          npm install
          npm run dev & 
          sleep 10

      - name: Install dependencies and lint (Framework)
        working-directory: ./framework
        run: |
          npm install
          npm run lint

      - name: Run seed script
        working-directory: ./framework
        run: npx tsx src/scripts/seed.ts

      - name: Run tests
        working-directory: ./framework
        run: npm run test
